# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/peel/pre-commit-hooks
    rev: 22cf6b4f499ede079f8e53ee5c7146cf69955bf3
    hooks:
    -   id: ghissue-message
        args: [.git/COMMIT_EDITMSG, snowplow, snowplow]
